### ISSUE TITLE
「一時停止」のユーザーをみやすく

### ISSUE THREAD

**Issue by miya0001** [geolonia/app.geolonia.com#111]
行をグレーアウトさせるなどなど

**Comment by kamataryo** [comment]
@miya0001 今のところこのチップを出すようにしているのですが、どうでしょう？
<img width="589" alt="Screenshot 2019-11-08 17 52 47" src="https://user-images.githubusercontent.com/6292312/68462775-98a7e280-0250-11ea-8898-504303e4bf15.png">
