### ISSUE TITLE
存在しないユーザーをチームに招待する際には、アカウントへの招待メールを送信する

### ISSUE THREAD

**Issue by miya0001** [geolonia/app.geolonia.com#131]
![](https://www.evernote.com/l/ABWwCitnXIhIMLDtk9j1zqFa9UgYZMkQD_EB/image.png)

現状は単にエラーを出しているが招待メールを送るようにする。

**Comment by kamataryo** [comment]
#567, #547 およびサーバーサイドの対応で実装
