### ISSUE TITLE
API一覧のページ切り替え機能が動作していない

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#149]
![page-bug](https://user-images.githubusercontent.com/43288418/68541202-e141d600-03df-11ea-991e-498a6c069bef.gif)

**Comment by kamataryo** [comment]
TODOs:
- Material UI の `@material-ui/core/Table` の使い方を確認して対応する https://material-ui.com/components/tables/#sorting-amp-selecting
