### ISSUE TITLE
APIキー作成時に保存ボタンを連打すると複数のAPIが作成される

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#150]
![create-bug](https://user-images.githubusercontent.com/43288418/68541244-57ded380-03e0-11ea-853b-aabb25b73a98.gif)

**Comment by kamataryo** [comment]
TODOs:
- `<Save />` コンポーネントを回収してリクエスト中はボタンを不活化する

**Comment by kamataryo** [comment]
該当箇所:
https://github.com/geolonia/app.geolonia.com/blob/1c878782d447821d01103683d4f377bc8f44729d/src/components/custom/AddNew.tsx#L101-L106

修正方法:
`status === "requesting"` の時にボタン要素を不活化する

**Comment by nztm** [comment]
[Bug]
PR patch-150で保存ボタンの連打はできなくなったものの、ローディングアニメーションが終わるタイミングで一瞬だけdisabledが外れるため、2個までは作成できてしまう

![test](https://user-images.githubusercontent.com/43288418/68544008-d1d38480-0401-11ea-8265-a4af02276849.gif)

**Comment by kamataryo** [comment]
TODO:
- check which occurs earlier closing modal or finishing requesting.

**Comment by kamataryo** [comment]
原因: キー作成のステータスが `success` になったときに、ボタンが有効化され、ダイアログが消える前までにそれを押せる瞬間がある。この時にボタンを押されるとキーが重複で作られる。
