### ISSUE TITLE
APIを削除するときに削除ボタンを連打すると他のAPIも削除される

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#151]
![delete-bug](https://user-images.githubusercontent.com/43288418/68541258-8197fa80-03e0-11ea-8521-75f1820294f8.gif)

その後、ページを再読み込みするとAPIの一覧が順番が変わった状態で表示される。
<img width="1680" alt="スクリーンショット 2019-11-10 14 11 13" src="https://user-images.githubusercontent.com/43288418/68541277-b73ce380-03e0-11ea-9a60-733802316851.png">

**Comment by miya0001** [comment]
@kamataryo これ削除のキーになってるものを見直したほうがいいかもですね。

**Comment by kamataryo** [comment]
そうですね。
今は API キーは配列で持っていて、どの API キーを削除しようとしているかは配列のインデックスをキーとして特定しています。

API キーの値でステートを検索するようにすると、UI の動作がもっさりするようになってデータが多くなるのに応じてスケールしないため、配列または連想配列を使うこと以外は考えていません。
また、連想配列に変えるとすると、ステートの更新ロジックが過度に複雑になると思っています。

なので、配列のインデックスで特定した上で、キーの値が一致しているかを確認するようにしようと思います。それと UI 上でのボタン不活化などの制御をします。
