### ISSUE TITLE
APIキーの名前を半角/全角スペースで生成できる問題を修正する

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#157]

**Comment by kamataryo** [comment]
Similar to #158

The issued lines:
- Input element: https://github.com/geolonia/app.geolonia.com/blob/master/src/components/Maps/APIKey.tsx#L175-L183 
- Save button: https://github.com/geolonia/app.geolonia.com/blob/master/src/components/Maps/APIKey.tsx#L206

**Comment by kamataryo** [comment]
@nztm This patch is a good example of this issue!
https://github.com/geolonia/app.geolonia.com/pull/161/files
