### ISSUE TITLE
プロフィール設定で名前を半角/全角スペースのみにできる問題を修正する

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#158]
![space](https://user-images.githubusercontent.com/43288418/68633036-bb2d4a80-0533-11ea-974f-7482c3815ad9.gif)

**Comment by kamataryo** [comment]
確かに名前を空にできるのよくないですね。是非修正しましょう！

**Comment by kamataryo** [comment]
TODO:
- [ ] 名前の前後に半角スペース・全角スペースが入っていた時に取り除く
- [ ] 半角スペース、全角スペースのみの名前が入力されている時は、 Save ボタンを押させない

該当箇所:
- 名前の入力フォーム https://github.com/geolonia/app.geolonia.com/blob/master/src/components/User/profile.tsx#L118-L125
- Save ボタン https://github.com/geolonia/app.geolonia.com/blob/master/src/components/User/profile.tsx#L156

**Comment by kamataryo** [comment]
specs:
- Use `onBlur` props 
- When blur, use `String.prototype.trim()` method to remove unnecessary whitespaces
- Save button should be disabled if `name` value is invalid
