### ISSUE TITLE
登録時のメールの改善

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [geolonia/app.geolonia.com#202]
# 現状
* タイトル
  * 検証コード
* 本文
   * 検証コードは 049070 です。

# 修正案
* タイトル
  * メール認証[Geolonia]
* 本文
   * Geoloniaにご登録いただきありがとうございました。アクティベーションコード 049070 です。このメールに見覚えが・・・

# 画面
* 検証コード > アクティベーションコード

![Screenshot](https://user-images.githubusercontent.com/8207033/71898830-a240be80-319d-11ea-8c0b-fc18b82fcc8d.png)

# そもそも
* クリックするのが理想

**Comment by miya0001** [comment]
以下QiitaTeamの例

```
geolonia チームオーナー
xxxx さま

この度はトライアルのご利用、誠にありがとうございます。
下記へアクセスし、メールアドレスの認証を完了させてください。

メールアドレスの登録を完了する

※認証の有効期限は24時間です
有効期限が切れた場合はチーム設定より、メールアドレスを再設定してください。

Qiita Team では、簡単にチーム内でドキュメントの共有、コミュニケーションができます。
Qiita Team を使って、あなたのチームの生産性を高めましょう！

まずはあなたのチームにメンバーを招待しましょう！
Qiita Team のご利用方法はこちらから
https://teams.qiita.com/guide

—
※もしこのメールにお心当たりが無い場合や、ご不明な点がある場合は、お手数ですがsupport@qiita.comまでご連絡ください。

Increments.Inc
Qiita Teamサポートチーム
support@qiita.com

お問い合わせ |Twitter |Facebook
```

**Comment by kamataryo** [comment]
Netlify のケース

```text
Verify Your Email
Please use the following 4 digit code to verify your email:
123456
Didn't request a verification code? Just ignore this email or contact our support.
```

**Comment by kamataryo** [comment]
変更しました。

![IMG_4783D7AEAF3E-1](https://user-images.githubusercontent.com/6292312/72239308-ef041980-3623-11ea-8a87-99221f2efd19.jpeg)
