### ISSUE TITLE
チーム名の変更ができるようにする

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [geolonia/app.geolonia.com#205]
チーム名の変更ができるようにする。
エラーメッセージを正しく表示する。（現状は、`パスワードの変更を失敗しました。`となる）

https://app.geolonia.com/#/team/general

現状は、

![errer](https://user-images.githubusercontent.com/8207033/71939604-96cdb180-31f6-11ea-9d65-b333b567857a.png)

# 背景

長いチーム名で表示がどうなるのかチェックしようとしていました。

**Comment by kamataryo** [comment]
メッセージについては 75626cd で修正

**Comment by kamataryo** [comment]
対応しました。
