### ISSUE TITLE
メンバー権限の説明文変更

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [geolonia/app.geolonia.com#207]
優先度[低]
必要性[低]

メンバー権限の説明文変更
https://app.geolonia.com/#/team/members

* 変更すべきと思った理由
  * メンバーが「メンバーの管理」ができないのがわかればそれでいいかなと思いました。
  * ドキュメントなどで補足されていく内容だと思いますのでやらなくてもいいと思います。

1. やるかどうか、文言を決める（宮内さんお願いします。）
2. 権限の説明文変更

# 現状
権限を変更
atsufumi.yoshikawa+1 の権限を選択して下さい。

オーナー
チームに関する全ての管理者権限があります。

メンバー
このチームの全てのリソースにアクセスできます。

![スクリーンショット 2020-01-08 9 15 08](https://user-images.githubusercontent.com/8207033/71939861-69353800-31f7-11ea-8d9c-d0a4e41e7ad1.png)

# 変更案
権限変更
atsufumi.yoshikawa+1 の権限を選択して下さい。

オーナー
メンバーの管理を含むチームに関する全ての管理者権限があります。

メンバー
このチームの全てのリソースにアクセスできます。

**Comment by miya0001** [comment]
具体的な内容がほしい。たとえば管理者はチームメンバーの招待ができる。

**Comment by kamataryo** [comment]
closed by #270
