### ISSUE TITLE
APIキーの「URL のリスト」の必要性が分かるようにする

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [geolonia/app.geolonia.com#210]
優先度[低]
必要性[低]

APIキーの「URL のリスト」の必要性が分かるようにする

※基本的には、APIキーのページ、とてもわかりやすいと思います。

# 対応案1

`URLのリスト`を`表示を許可するURLリスト`にする

# 対応案2

説明を追加
例えば、`/*`などの説明があるとよりわかりやすい気もしました。

参考までGoogleのAPIのページです。

![API_キーの制限と名前変更_–_API_とサービス_–_Japonismes_–_Google_Cloud_Platform](https://user-images.githubusercontent.com/8207033/71941593-adc3d200-31fd-11ea-9689-85283f07ef41.png)

```
キー使用のリクエストを、指定したウェブサイトに制限します。
空白のままにすると、API キーはすべてのウェブサイトからリクエストを受け入れます。
```

```
API キーを特定のウェブサイトに制限するには
API キーを使用できる URL を制限するには HTTP リファラーを使用します。

リファラーを設定できる URL の例を示します:

正確なパスが含まれる特定の URL: www.example.com/path
ワイルドカード アスタリスク（*）を使用する、1 つのサブドメイン内の任意の URL: sub.example.com/*
ワイルドカード アスタリスク（*）を使用する、1 つのドメイン内の任意のサブドメインまたはパスの URL: *.example.com/*
標準ではないポートを含む URL: www.example.com:8000/*
注: 現時点でクエリ パラメータおよびフラグメントはサポートされていません。これらを HTTP リファラーに含めた場合は、無視されます。
```

**Comment by miya0001** [comment]
CORS から Referer に変わったのでその旨を修正する。
