### ISSUE TITLE
チームの写真が上がるようにする

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [geolonia/app.geolonia.com#211]
# 上がらなかったもの

pngのファイル 16kb 302x268 sRGB
jpgのファイル 278kb 1280x720 RGB

# 出てくるエラー
![Screenshot (3)](https://user-images.githubusercontent.com/8207033/71942259-f67c8a80-31ff-11ea-9eec-aa7c09c13135.png)

**Comment by kamataryo** [comment]
Bucketの権限確認

**Comment by kamataryo** [comment]
S3バケットの設定を修正しました。

```shell
$ aws s3api get-bucket-cors --bucket geolonia-user-avatar-v1
{
    "CORSRules": [
        {
            "AllowedHeaders": [
                "*"
            ],
            "MaxAgeSeconds": 60,
            "AllowedMethods": [
                "PUT",
                "GET"
            ],
            "AllowedOrigins": [
                "*"
            ]
        }
    ]
}
```

**Comment by kamataryo** [comment]
<img width="1356" alt="Screenshot 2020-01-13 00 21 57" src="https://user-images.githubusercontent.com/6292312/72221105-ba984b00-359a-11ea-8030-b51dda45d894.png">
