### ISSUE TITLE
サインアップ時にすでに存在しているメアドでサインアップした時のメッセージが不親切

### ISSUE THREAD

**Issue by miya0001** [geolonia/app.geolonia.com#213]
![Dashboard_-_Geolonia](https://user-images.githubusercontent.com/309946/72217403-6bd5bb80-3570-11ea-89d1-fb0b7cea3e6f.png)

**Comment by kamataryo** [comment]
done at #275 
![Uploading Screenshot 2020-03-31 12.21.13.png…]()
