### ISSUE TITLE
サインアップのエラー時にレイアウトが崩れる

### ISSUE THREAD

**Issue by miya0001** [geolonia/app.geolonia.com#216]
![](https://www.evernote.com/l/ABU5XMaFoL9KsZ6P_1C-QShkjQQ-Vc_fOl4B/image.png)

ウインドウの高さが小さいときだけかも

**Comment by kamataryo** [comment]
<img width="1552" alt="Screenshot 2020-01-13 23 08 58" src="https://user-images.githubusercontent.com/6292312/72262184-c3038b00-3659-11ea-92fe-f2576abdc565.png">
