### ISSUE TITLE
ユーザーのブラックリスト機能

### ISSUE THREAD

**Issue by miya0001** [geolonia/app.geolonia.com#228]
サインアップとログインを禁止するブラックリストがほしい。
メールのエイリアスにも対応したやつ。

Note: メールのエイリアスを使った複数のサインアップは許可したい。ただし上のブラックリストにマッチしたらエイリアスも含めてすべてブロックしたい。

**Comment by kamataryo** [comment]
This feature is working and will be useless at open beta phase in near future.
<img width="1392" alt="Screenshot 2020-03-05 14 21 26" src="https://user-images.githubusercontent.com/6292312/75950505-be868080-5eec-11ea-95e9-12a1eec75372.png">
