### ISSUE TITLE
自分のメールアドレスに招待を送ると招待ボタンが消える

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#233]
自分で自分のメールアドレス宛にチーム招待を送るとInviteボタンが消えます。
チームの削除もできなくなったので、おそらくOwner権限がMember権限に上書きされています。

![](https://user-images.githubusercontent.com/43288418/75016663-d8789a00-54ce-11ea-8982-ea65ca665326.gif)

**Comment by kamataryo** [comment]
TODO: API 修正
