### ISSUE TITLE
チーム名を半角スペースにすると表示が崩れる

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#234]
チーム名を半角スペースにするとプルダウンのheightが小さくなるようです。
全角の場合は問題ないようです。

![](https://user-images.githubusercontent.com/43288418/75016924-618fd100-54cf-11ea-85c9-6a8b18f7da76.gif)

**Comment by miya0001** [comment]
@kamataryo 

入力に対して以下のフィルターをかけてください。

1.  ASCII文字列はすべて半角に変換
2. `String.trim()` で前後のスペースを削除
