### ISSUE TITLE
チーム削除のフィールドの文言に違和感がある

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#235]
チーム削除時のフィールドの「パスワードを確認」は文言を変えたほうがいいかもしれません。
パスワードを入力するのかと勘違いされそうです。

<img width="605" alt="スクリーンショット 2020-02-21 17 01 31" src="https://user-images.githubusercontent.com/43288418/75017121-c0ede100-54cf-11ea-962c-4dba0bde8501.png">

**Comment by miya0001** [comment]
@nztm これ挑戦してみてください。

**Comment by nztm** [comment]
これ、「パスワードを確認」をなにに変えましょう。

「Enter delete」「delete と入力してください」でもいいかもしれないのですが、
Label自体を削除してしまっても問題はないのかなと思わないこともなく。

**Comment by miya0001** [comment]
そうですね。label 自体を削除しましょう。
