### ISSUE TITLE
翻訳されていない箇所がいくつか存在する

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#237]
「Invite」が「招待」になっているのに対して「New」は「New」のままになっているので、
「新規作成」などに翻訳したほうがいいかもしれない(?)

<img width="1039" alt="スクリーンショット 2020-02-21 17 53 39" src="https://user-images.githubusercontent.com/43288418/75018846-2c857d80-54d3-11ea-8f3e-d86aef70b896.png">

---

チーム設定の「We’ll send receipts to this inbox.」が翻訳されていない。

<img width="685" alt="スクリーンショット 2020-02-21 17 51 56" src="https://user-images.githubusercontent.com/43288418/75018850-2e4f4100-54d3-11ea-8133-74d9c47f6d91.png">

**Comment by miya0001** [comment]
@nztm お願いします。
