### ISSUE TITLE
画面幅が狭いときにCodeボックス内を選択するとはみ出す

### ISSUE THREAD

**Issue by nztm** [geolonia/app.geolonia.com#240]
画面幅が狭い時に選択すると画像のようになってしまうので、
横スクロールができるようにしたほうがいいかもしれないです。

overflow: scroll;を入れるだけで解決できそうです。

<img width="332" alt="スクリーンショット 2020-02-22 9 31 30" src="https://user-images.githubusercontent.com/43288418/75082312-4b792380-5556-11ea-9260-b1bbc4dafc35.png">

**Comment by miya0001** [comment]
```
word-break: break-all;
```

がいいかもですね。

**Comment by miya0001** [comment]
こっちかな。
https://developer.mozilla.org/ja/docs/Web/CSS/overflow-wrap

どれがベターかよくわからないので調べて対処していただけるとー。

**Comment by nztm** [comment]
了解ですー！
