### ISSUE TITLE
港区の区役所・総合支所 GeoJSONをアップロードした時に画面が真っ白になる

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#343]
東京オープンデータカタログの港区の区役所・総合支所 GeoJSONを、GeoJSON APIにアップすると画面が真っ白になってしまう。

### アップロードしたGeoJSON
https://opendata.city.minato.tokyo.jp/dataset/74c06ebb-47dd-4fe1-8ba7-a5be60d2a448/resource/f1a1056b-a00e-4c12-8a78-288e0eee7ba0/download/minatokushisetsujoho_kuyakusyo.json

### スクリーンショット
![スクリーンショット 2021-06-25 11 29 53](https://user-images.githubusercontent.com/8760841/123360766-d5048f80-d5a8-11eb-8da3-cc21e92d7a58.png)

**Comment by naogify** [comment]
エラーメッセージが `Error: each element in a position must be a number` となっている。

港区の区役所・総合支所の GeoJSON の 緯度経度が文字列型なのが原因かも。

```
            "geometry": {
                "type": "Point",
                "coordinates": [
                    "139.735091",
                    "35.660657",
                    0
                ]
            },
```

**Comment by kamataryo** [comment]
https://datatracker.ietf.org/doc/html/rfc7946#section-3.1.1

>  A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.  Altitude or elevation MAY be included as an optional third
   element.
   
`[lon: number, lat: number]` が GeoJSON 的には正しいので、元データが壊れているわけですが、修理するような処理を入れるかどうかですね。

**Comment by kamataryo** [comment]
真っ白になるのは直すべきですね。

**Comment by naogify** [comment]
確かに、エラーメッセージは必要ですね。

型変換の件は、型変換してあげた方がユーザーにとって親切だと思いました。。（港区の他のデータにも文字列型の緯度経度があったので。優先順位は低で良いと思います。）

**Comment by kamataryo** [comment]
- エラーハンドリングの修正に関しては #348 の後に対応
- GeoJSON のフォーマット変換についてはひとまず優先度は低い

**Comment by kamataryo** [comment]
この件、クライアント側で GeoJSON を処理する必要がなくなったので、対応が不要になりました。
