### ISSUE TITLE
origin 認証の設定ができるようにする

### ISSUE THREAD

**Issue by keichan34** [geolonia/app.geolonia.com#352]
Requires geolonia/api.geolonia.com#174

**Comment by keichan34** [comment]
Public = false の時のみ、表示させる

**Comment by naogify** [comment]
@kamataryo 

allowedOrigins の 保存と取得の仕方書いてくれていたの確認しました。ありがとうございます!

https://github.com/geolonia/api.geolonia.com/issues/174#issuecomment-874412920

**Comment by naogify** [comment]
Closed by #363
