### ISSUE TITLE
GeoJSON をアップロードする欄を調整

### ISSUE THREAD

**Issue by keichan34** [geolonia/app.geolonia.com#355]
* データが無いときは大きくして(現状の地図？よりちょっと小さく)
* データがあるとき(地図が表示されているとき)は現状と同じぐらい
* GeoJSONをアップロード・CSVをアップロードのアイコンを並ぶようにするイメージ(今はGeoJSONのみだけど)
* 時間があればプログレスバー的なやつがほしい

**Comment by kamataryo** [comment]
アップロードのAPI アクセスの詳細:
1. SignedURL を取得するエンドポイント（`GET https://api.app.geolonia.com/dev/geojsons/${geojsonId}?teamId=${teamId}`）にアクセスして、URL を取得
2. 1の URL に GeoJSON を PUT で投げる

アバターの更新のロジックを参照。
https://github.com/geolonia/app.geolonia.com/blob/1f7dca234fd95ef503d2453964313ea9c354123d/src/api/teams/put-avatar.ts
