### ISSUE TITLE
APIキーとGeoJSONAPI の オリジン入力フォームで * が消えてしまう

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#364]
ワイルドカードを指定して、「保存」→ 再読み込みすると下の画像のようにワイルドカードが消えてしまう。

![スクリーンショット 2021-07-08 17 59 11](https://user-images.githubusercontent.com/8760841/124894035-3ea78380-e016-11eb-80c7-374f0efd5e54.png)
![スクリーンショット 2021-07-08 17 59 57](https://user-images.githubusercontent.com/8760841/124894257-71517c00-e016-11eb-9bbd-9f3e2e3371c1.png)

**Comment by kamataryo** [comment]
API サーバー側で修正済み。ついでに同様のロジックを本クライアントでも導入済み #423
