### ISSUE TITLE
プルダウンでスタイル変更時に、データが更新されない

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#367]
Related to #365 

GeoJSONをアップロード後に、プルダウンでスタイルを変更するとタイルが表示されない。

![スクリーンショット 2021-07-12 16 00 38](https://user-images.githubusercontent.com/8760841/125244449-52126180-e32a-11eb-9feb-3aa53a9645aa.png)

**Comment by keichan34** [comment]
https://github.com/geolonia/app.geolonia.com/blob/develop/src/components/Data/MapEditor.tsx#L85
styleが変更したときに、ここの map.setStyle が呼び出される。
styleが更新されるとき、おそらく simplestyle を適用し直す必要があると思うけど、それがうまく適用されていないのかな。。？

**Comment by naogify** [comment]
master ブランチの GeoJSON を表示する版でマップのスタイルを変更した時にこの現象が起きなかったのは、GeoJSON の simplestyle をMapboxDraw で適用してたからなんですね。。。

https://github.com/geolonia/app.geolonia.com/blob/develop/src/components/Data/MapEditor.tsx#L108

**Comment by keichan34** [comment]
embedで対応してみますー。

**Comment by keichan34** [comment]
https://github.com/geolonia/embed/pull/215
