### ISSUE TITLE
GeoJSONを再アップロード時にデータが更新されない

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#368]
GeoJSONを一度アップロード後に、再アップロードするとタイルが更新されない。

更にもう一度アップロードすると更新されるので、更新ステータスの取得部分に原因がありそう。

![スクリーンショット 2021-07-12 15 58 39](https://user-images.githubusercontent.com/8760841/125244220-0790e500-e32a-11eb-94a7-f727ed2de59c.png)

**Comment by naogify** [comment]
Related to #365

**Comment by keichan34** [comment]
gvp_status = created のままになっているため、最新のステータスが取得されていない
