### ISSUE TITLE
app-dev.geolonia.com で作成したAPIキーで地図を表示できるように

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#395]
> 地図を表示する手順を試してみようと、https://app-dev.geolonia.com/ で作成したAPIキーを使い、自分のブログに地図を追加してみると、403でベースの地図が表示されませんでした。原因って何か分かりますでしょうか、、？
テストした環境はこちらです。
https://naoki-is.me/archives/713

<img width="1440" alt="スクリーンショット 2021-07-16 15 44 17" src="https://user-images.githubusercontent.com/8760841/125910093-ec726a82-8cd3-4f01-859c-c9071009c662.png">

## 解決法

stage=devの場合はstyle に source として追加している tileserver.geolonia.com をtileserver-dev.geolonia.com に置き換える必要がある。

**Comment by kamataryo** [comment]
@naogify こちらは解消済みだったと思いますので、クローズします 🙇
