### ISSUE TITLE
 管理画面トップのDeveloper's Blog の上には使い方を説明するコンテンツを追加する

### ISSUE THREAD

**Issue by kogumari** [geolonia/app.geolonia.com#408]

**Comment by ShinichiNishikawa** [comment]
Developers' blog の上に3つリンクする。

* **「チュートリアル」**:  管理画面を使って地図をウェブサイトに埋め込むまでの手順を説明しています。
* **「Embed API」**: コードブロックをカスタマイズして、サイズや○○などをカスタマイズするための方法を説明しています。
* 開発者用: Javascript API, カスタムスタイルなど、開発者向けの詳細

**Comment by kai4den** [comment]
@naogify ここはリリース一番目につくところなので、優先度高めかなと思いました @ShinichiNishikawa

**Comment by ShinichiNishikawa** [comment]
ニシカワ、コンテンツを提案します。

**Comment by ShinichiNishikawa** [comment]
全体のレイアウトはこのような様子

![IMG_5492のコピー](https://user-images.githubusercontent.com/1124652/127835576-ea0deec1-9d38-4b1d-91cf-4644b0bb330b.jpg)

以下は、docs.geolonia.com のトップページから read more を取ったもの。これを文言はタイトルと説明文はすごくわかりやすいのでそのまま貼り付ける。

<img width="1172" alt="スクリーンショット 2021-08-02 18 03 13" src="https://user-images.githubusercontent.com/1124652/127835616-47fd6440-eecb-45c3-802a-89862ceab83f.png">

ちなみに、ワンアイディア追加で、右下が空いているのでそこにサポートへの問い合わせフォームへのリンクを追加してもいいかもしれないと思った。

@naogify

**Comment by kamataryo** [comment]
NOTE: `GeoJSON仕様`へのリンクは含めない。
