### ISSUE TITLE
チーム設定 Member : Geolonia Proへのアップグレード

### ISSUE THREAD

**Issue by kogumari** [geolonia/app.geolonia.com#411]
Geolonia Proへのアップグレードできる場所が見当たらなかったので推測ですが、
8月1日時点で、Geolonia Proがないのであれば、「今後リリース予定」などとしたほうが良さそう。

**Comment by kogumari** [comment]
@keichan34 確認いたしました！

**Comment by keichan34** [comment]
ありがとうございました :bow:
