### ISSUE TITLE
左メニューの階層をもうちょっとわかりやすく表示する

### ISSUE THREAD

**Issue by keichan34** [geolonia/app.geolonia.com#417]
現状ヘッダーとサブが区別がちょっとむずかしい。。

**Comment by kai4den** [comment]
こちらもここに追加で。

- 左メニューの見出しはカテゴリを「地図作成」、クリッカブルな見出しを「設定」としたい
- 「設定」クリック後の右メイン画面は見出しを「設定」とし、その下に中見出しとして「APIキー一覧」としたい。

以下画面参照

![image](https://user-images.githubusercontent.com/7685434/127873505-8f642298-2f05-42e4-bec8-184c31b1c639.png)
