### ISSUE TITLE
「新しいAPIキーを作成」のポップアップを削除

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#425]
「新しいAPIキーを作成」のポップアップが一手間あるので、

<img width="1440" alt="スクリーンショット 2021-07-29 10 57 09" src="https://user-images.githubusercontent.com/8760841/127419654-b28a1872-3d6d-48a0-abce-f7634352e858.png">

APIキーを新規作成時に、名前のデフォルト値を「APIキー + 連番」にすることで解決できる。それでユーザーの1アクションを減らせる。

<img width="1183" alt="スクリーンショット 2021-07-29 10 57 48" src="https://user-images.githubusercontent.com/8760841/127420024-7abf6733-b1de-45c8-9365-ff3fd262d237.png">

**Comment by ShinichiNishikawa** [comment]
「地図を作成」ボタンクリック後。

* 見出しを「地図」にする
* 小見出しとして「API キーの一覧」
* 小見出しの下に説明文「あなたのウェブサイトに地図を埋め込み表示するためにはAPIキーが必要です」
* ポップアップなし

**Comment by keichan34** [comment]
```
APIキー (nagoify が 2021-08-03 作成)
```

**Comment by naogify** [comment]
今回のリリースで含めるかは分からないですが、`https://app.geolonia.com/#/api-keys/new` にアクセスすると、APIキー新規作成ページに飛べると良さそう。

そうすると、トップページのリンクボタンから、`https://app.geolonia.com/#/api-keys/new` へ飛ばすことで、1ステップでAPIキーを作成できる。

![スクリーンショット 2021-08-03 11 33 28](https://user-images.githubusercontent.com/8760841/127948608-2d03920c-0865-4fc5-80ce-addb163cac0b.png)

**Comment by kamataryo** [comment]
@naogify あ、なるほど。同時にこの変更が容易かを確認します。

**Comment by kamataryo** [comment]
@naogify @keichan34 こちら作ってみました。操作感とかイメージに合ってますか？
それと、 #462 との整合性ってどんな感じでしょう？
https://deploy-preview-466--geolonia-app-dev.netlify.app/

**Comment by keichan34** [comment]
@kamataryo よさそうですね。。作成後、自動で詳細ページにページ遷移できれば完璧かな？

**Comment by naogify** [comment]
@kamataryo ありがとうございます。自分も自動でページ遷移できれば完璧だと思います…！

**Comment by naogify** [comment]
#462 とは、ユーザーの操作ベースでは整合性が取れているのですが、コードベースでコンフリクトが起こりそうなので、そこだけお願いするかもしれません。。🙇‍♂️

**Comment by kamataryo** [comment]
今はページ遷移をせずにスナックバーを出してますけど、ページ遷移後に `キーができました。` のスナックバーが出るのがいいかな。
