### ISSUE TITLE
長方形の画像をアップロードすると、プロフィールページの画像が長方形になる。

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#427]
<img width="1181" alt="スクリーンショット 2021-07-29 11 49 12" src="https://user-images.githubusercontent.com/8760841/127423829-9a4d2927-cfca-45d5-a632-39ea1c1b0a14.png">

テスト画像（長方形）
![IMG_0028](https://user-images.githubusercontent.com/8760841/127423838-1e599286-08a6-4a33-b040-e3c265a7a5bd.jpg)

**Comment by kamataryo** [comment]
これ、 material-ui の `<Avatar />` というコンポーネントが丸くトリミングしているようです。
チームの方のアバターでは切り抜かずに表示しているだけです。
アスペクト比は変わっていなかったです。

@naogify トリミングせずにそのまま表示するといいかと思いますがどう思いますか？

<img width="524" alt="スクリーンショット 2021-07-30 9 19 50" src="https://user-images.githubusercontent.com/6292312/127581410-e95db009-9d46-4276-92e9-9ca05d7ad09e.png">

**Comment by naogify** [comment]
@kamataryo 

プロフィール画像がほかの場所（ヘッダー等）で丸くトリミングするので、プロフィールページでも丸くトリミングしてあげると、アップロード時に見栄えの表示確認できるので良いかな？と思いました。（例：自分の画像が中心に来てないので別のアスペクト比の画像を再アップロードしようとか…）

どうでしょうか、、、？

**Comment by kamataryo** [comment]
なるほど。意図了解です。
CSS 1,2行で済むのでやっちゃいますね。

**Comment by naogify** [comment]
ありがとうございます…！！

**Comment by kamataryo** [comment]
あと直接関係ないのですが、ここの画像はアイコンであって写真とは限らないのでテキストがおかしかったです。
一緒に `新しい写真をアップロード` -> `アイコンを変更` のように変えようと思います。翻訳が絡むので #429 の後で。

**Comment by kamataryo** [comment]
でも Picture でいいのかな。GitHub だとこうなっている。これは踏襲しようと思います。

- organization -> Upload new picture
- user -> change your avatar

**Comment by naogify** [comment]
了解です…！よければ #429 で対応します。

ちょうど自分も Facebook とかを調べてました。。。

ちなみに、「新しい画像をアップロード」はどう思います？？

![スクリーンショット 2021-07-30 9 56 08](https://user-images.githubusercontent.com/8760841/127583857-59527704-bc2b-48e9-9c68-ad51d32855c0.png)
![スクリーンショット 2021-07-30 9 55 53](https://user-images.githubusercontent.com/8760841/127583864-531e823a-9cde-44a4-bfe1-afed4de282f0.png)
