### ISSUE TITLE
トップページに「Create Map」ボタンを追加

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#438]
ほとんどのSaaSがトップページに「Create 〇〇」ボタンを表示して、それをクリックすることで最初のプロジェクトを作成できる様にしている。Geolonia にも「Create Map」のようなボタンが欲しい。

ボタンを押した後のフローは要検討。

GitHub
<img width="600" alt="スクリーンショット 2021-08-01 16 39 25" src="https://user-images.githubusercontent.com/8760841/127763476-a063e3b1-8683-4932-98f7-32b7f06f01d3.png">

Vercel
<img width="600" alt="スクリーンショット 2021-08-01 16 39 04" src="https://user-images.githubusercontent.com/8760841/127763483-8e580959-159b-4fdc-838a-9af04bfc01cf.png">

Netlify
<img width="600" alt="スクリーンショット 2021-08-01 16 38 51" src="https://user-images.githubusercontent.com/8760841/127763487-eb85e928-187e-4e94-b7db-571ee037256e.png">

Auth0
<img width="600" alt="スクリーンショット 2021-08-01 16 38 37" src="https://user-images.githubusercontent.com/8760841/127763491-80264bdd-8a12-4f63-8fb3-0f945cdf5445.png">

**Comment by naogify** [comment]
イメージ

<img width="1396" alt="スクリーンショット 2021-08-01 16 39 39" src="https://user-images.githubusercontent.com/8760841/127763543-15c6a14a-a09f-4c37-9f3e-2359dedc1db4.png">

**Comment by ShinichiNishikawa** [comment]
* わかりやすさ優先なら、日本語がいいと思うので検討: 「地図作成」「地図を作る」「新しい地図を作る」
* バナーにあるメッセージも変更したい。今はデータのアップロードをさせないので、いったん地図を作るに直行できるように。

```
# 地図を作ろう

地図のデザインや表示位置の初期設定をしてください。
そのあと、表示されたHTMLのコードブロックをあなたのウェブサイトにコピー・アンド・ペーストすると、作成した地図が表示されます。

[ボタン]
```

みたいに言葉で説明したらわかりやすいかな。

**Comment by naogify** [comment]
日本語化と、初期リリースの地図作成に絞ったメッセージに変更する件、良いですね…！

**Comment by ShinichiNishikawa** [comment]
@naogify いったんこちら提案します。


![IMG_5489のコピー](https://user-images.githubusercontent.com/1124652/127832380-d69ea3bf-d1eb-49e8-a10e-2da1f0a0d6d7.jpg)

## Geolonia 地図の使い方

### 1. API キーの取得

この管理画面でAPIキーを発行し、地図を表示するウェブサイトのURLを設定します。

### 2. ウェブサイトに地図を設置

API キー発行画面に生成された HTML, Javascript, CSS をウェブサイトにコピーすると、地図が表示されます。

### 3. カスタマイズ

<a href="https://docs.geolonia.com/embed-api/">Embed API 仕様</a>を参照し、表示させた地図の座標（緯度、経度）、ズームレベル、マーカーやポップアップを設定します。

ドキュメンテーションの[Javascript API](https://docs.geolonia.com/javascript-api/) や[カスタムスタイル](https://docs.geolonia.com/custom-style/)を参照して、スタイリングや本格的な地図アプリの開発ができます。

[ボタン: 地図を作成する]

**Comment by naogify** [comment]
@ShinichiNishikawa 
ありがとうございます！これを踏まえて検討&実装してPR送ります…！

**Comment by kamataryo** [comment]
@naogify こちらとじますね。ありがとうございました！
