### ISSUE TITLE
サインアップページに利用規約の確認チェクボックスを追加。

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#441]

**Comment by keichan34** [comment]
@ShinichiNishikawa @kai4den 
現状
<img width="391" alt="Screen Shot 2021-08-03 at 14 26 48" src="https://user-images.githubusercontent.com/1064513/127962699-8eca6115-3293-42e6-bcf2-8ffe178b8b65.png">

利用規約はチェックボックスにする必要があるんですかね？
多分このイッシュは最初「メールする同意は得てないから一斉メールするのはしないほうがいいよね。。」みたいなところで始まったと思うんですが、このイッシュを「サービスの更新などがあるときにのメールを希望します」的なチェックボックスを入れるというように変えましょうか？
