### ISSUE TITLE
ダッシュボードリニューアルの通知

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#442]
ウェルカムボードの上か下に、「ダッシュボードリニューアルの通知」を出す。

リリースの記事へのリンクする。

（~~GeoJSON API~~ は二週間程度復活の予定ですが、それまでに復活させたい方はお問い合わせください）

![スクリーンショット 2021-08-02 15 00 19](https://user-images.githubusercontent.com/8760841/127811463-d289247f-0466-42fb-aebb-f9c595617739.png)

**Comment by ShinichiNishikawa** [comment]
文言候補

```
管理画面を[リニューアルしました](http://example.com/リニューアルのリリース記事か開発者ブログ)。以前提供していたGeoJSON APIは、近日再度リリース予定です。すぐに設定変更などが必要な方は[ご連絡ください](http://example.com/問い合わせフォームへ)。
```

**Comment by keichan34** [comment]
> 管理画面を[リニューアルしました](http://example.com/リニューアルのリリース記事か開発者ブログ)。GeoJSON APIは機能改修を行っています。そのため、以前提供していたGeoJSON APIの管理画面は現在アクセスできません。データのダウンロードが必要の場合、[ご連絡ください](...)。
