### ISSUE TITLE
招待できるメールの説明を追加

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#444]
招待できるユーザーのメールは、既にGeoloniaでアカウント作成しているもののみの説明を追加

<img width="1149" alt="スクリーンショット 2021-08-02 15 37 23" src="https://user-images.githubusercontent.com/8760841/127815003-61d1a95b-d595-4759-af64-1dc1147d9e6b.png">

**Comment by keichan34** [comment]
@kai4den 

> 招待するユーザーのメールアドレスを記入してください。現在、招待を送信するためには宛先が既に Geolonia のアカウントを発行する必要があります。宛先が Geolonia のアカウントをお持ちではない場合は、作成してから招待を送信してください。

もっといい文章考えられますか。。？

<img width="612" alt="Screen Shot 2021-08-03 at 16 34 19" src="https://user-images.githubusercontent.com/1064513/127976236-b4e21d74-5d4b-49b7-94ba-4e06d6eac642.png">

**Comment by kai4den** [comment]
@naogify 
意外にむずいですねこれ。こんなかんじでいかがでしょう。

> 招待するユーザーのメールアドレスを入力してください。
> 
> ※注意：現在のことろ、チームに招待できるのはGeolonia Mapsのユーザー登録が完了しているメールアドレスのみとなりま> す。招待したい宛先がGeolonia Mapsにまだ登録していない場合は、ユーザー登録を済ませてから招待を送信してください。

**Comment by kai4den** [comment]
誤字ｗ
