### ISSUE TITLE
APIキーの設定ページのレイアウト変更

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#448]
このページに来たときに設定しているのがAPIキーなのであれば、一番目立つところへ移動させるとわかりやすい。
また、このページのメインコンテンツである名前、URLのリストについても白いボックスの中に入れてはどうか。

<img width="1950" alt="スクリーンショット 2021-08-02 19 01 22" src="https://user-images.githubusercontent.com/1124652/127843803-9781ca8d-be54-41ca-9119-375c2b1a4e56.png">

### 以下、変更提案

* 右上にあったキーの表示を左側に
* 「設定」であることを明示して、コンテンツボックスの中に入れる
* 「名前」を、「APIキー管理用の名前」に
* 「URLのリスト」を、「このAPIキーの利用を許可するウェブサイトのURLリスト」に
* 保存ボタンもこのボックスの中に入れて、左寄せ、あるいは大きくして保存ミスを防ぐ

**Comment by kai4den** [comment]
@ShinichiNishikawa とかぶったのでここでまとめます。追加で以下。

- 黄色いエリアの「URLのリストは…」の部分は、内容としてURLリストに登録するURLの形式のことを指しているので、実際にURLを入力するエリアと、その下にある罫線の間に入れたい（罫線の外だと別の項目に見えてしまう）
- サイドバーの地図作成機能は「APIキーの設定」の下に入れて1カラムにしたい。

わたくしの画像も参考まで貼っておきます。
![image](https://user-images.githubusercontent.com/7685434/127872907-8c57d6c3-bc77-4594-b174-d4e93d8814bb.png)

**Comment by naogify** [comment]
* 右上にあったキーの表示を左側に
* 「設定」であることを明示して、コンテンツボックスの中に入れる
* 「名前」を、「APIキー管理用の名前」に
* 「URLのリスト」を、「このAPIキーの利用を許可するウェブサイトのURLリスト」に
* 保存ボタンもこのボックスの中に入れて、左寄せ、あるいは大きくして保存ミスを防ぐ
* 黄色いエリアの「URLのリストは…」の部分は、内容としてURLリストに登録するURLの形式のことを指しているので、実際にURLを入力するエリアと、その下にある罫線の間に入れたい（罫線の外だと別の項目に見えてしまう）

このページの主目的がAPI キーの作成と設定なので、上記の変更は良いと思いました…！

**Comment by naogify** [comment]
> サイドバーの地図作成機能は「APIキーの設定」の下に入れて1カラムにしたい。

このページの主目的がAPI キーの作成と設定なので、地図の作成はサブ目的なのでサイドバーに配置でも良いかな？と思ったのですがどうでしょうか？

@kai4den  @ShinichiNishikawa

**Comment by naogify** [comment]
文言を「このAPIキーの利用を許可するウェブサイトのURLリスト」 → 「地図の表示を許可するURLのリスト」に文言を変更。

**Comment by ShinichiNishikawa** [comment]
@kai4den どうですか。

**Comment by kai4den** [comment]
@naogify 
> サイドバーの地図作成機能は「APIキーの設定」の下に入れて1カラムにしたい。
これは1カラムにするの結構工数的に大変、というのもありますか？ であれば表記修正とかで対応するのもありかなとおもいます。

> 地図の作成はサブ目的だと思うので、
これその通りだと思いますが、だからこそファーストビューで右サイドバーに見えているとむしろ目立っちゃうなーという印象です。下に下げておまけっぽくした方が目的果たせるかな、とおもったのですがいかがでしょう。
cc @ShinichiNishikawa

**Comment by naogify** [comment]
@kai4den 

> これは1カラムにするの結構工数的に大変、というのもありますか？ であれば表記修正とかで対応するのもありかなとおもいます。

工数的には変わらないです…！

> これその通りだと思いますが、だからこそファーストビューで右サイドバーに見えているとむしろ目立っちゃうなーという印象です。下に下げておまけっぽくした方が目的果たせるかな、とおもったのですがいかがでしょう。

なるほど…！では一度試してみます。

**Comment by ShinichiNishikawa** [comment]
HTMLなどのスニペット、このページではサブの目的ですが、ユーザーから見ると「あ、ここでコピペするのね！」と理解できるのでむしろ目立たせた方がよいとおもいます。
