### ISSUE TITLE
メニューの文言変更

### ISSUE THREAD

**Issue by naogify** [geolonia/app.geolonia.com#451]
以下Slackより転載

## 要望
左サイドメニューは「地図作成」またはそれに準じる単語のみにして、APIは右側のメインメニューに出したい

## 意図
このダッシュボードを利用するユーザーにとってわかりやすい画面にするためには、メニューの単語は「手段」ではなく「目的」（ユーザーがやりたいことが表示されている）としたいです。
ダッシュボードの場合、APIは「地図を発行するための手段」であって、目的は「地図を作る」ことなので、左側のメニューに唐突にAPIが出てくるのはユーザーを戸惑わせてしまうかなと思います。
とはいえ、実際に設定すべきことはAPIの管理であって、地図作成機能もAPIに紐づいていてかなり簡易的な作成機能でしかない補助的な状態なので、内容としてはAPIの設定なんだよ、ということは、クリックしてからのメイン画面で説明したい、と思います。

別のサービスで例えるなら、Webフォント発行サービスの場合、ユーザーはWebフォントを使いたいのであってAPIを取得したいわけではないので、メニューでは「Webフォントの設定」と表示されていて、その先に「Webフォントを使うにはAPIを取得する必要がありますよ」と説明すると理解してもらいやすいです。
※右側のメイン画面で表記したいと考えているのは、そうした説明文で補足しやすいからです

上記踏まえて、ちょっと画面のアイディアを作ってみましたので添付画像ご覧ください。

- 左メニューの見出しは「地図作成」にして、クリッカブルなところは「設定」とする
- 右のメイン画面では見出しは「設定」とし、その下の中見出しに「APIキー一覧」とする
- APIキー作成後は右のメイン画面に「APIキーの設定」「地図表示URLの発行」とわけて説明する

この形なら「ここはあくまでAPI管理画面である」ということも崩さずに、メニューはわかりやすくできるとおもうのですがいかがでしょうか。

我々は見慣れた画面ですべてを把握しているのですが、ユーザーにとっては初めて見る画面であることと、リリースのタイミングで画面を見た人が「よくわからないな」と離れてしまうと戻ってきてもらうことも大変になってしまうため、ここはしっかり考えて作りたいなと思います。

![image](https://user-images.githubusercontent.com/8760841/127938706-da1beb75-30ca-4ecb-af86-911a830f1058.png)
![image (1)](https://user-images.githubusercontent.com/8760841/127938712-4a47a0d2-2c75-4ae5-853b-67163636aa45.png)

（メニューの用語は「設定」でいいのかは悩みどころなのですが、APIキーも包括した見出しとして適切なものがほかに思い浮かばず……、アイディア合ったらほしいです）

**Comment by naogify** [comment]
@kai4den 

フィードバックありがとうございます…！

> ダッシュボードの場合、APIは「地図を発行するための手段」であって、目的は「地図を作る」ことなので、左側のメニューに唐突にAPIが出てくるのはユーザーを戸惑わせてしまうかなと思います。

確かにサイドメニューに地図の文言がどこにもないと、ユーザーを惑わせる可能性もあると思いました。


提案なのですが、見出しの文言を以下にするのはどうでしょうか？

```
- 地図
  - API キーの管理
```

## 理由

理由としては、

- 地図にAPIキーが必要ということがメニューの構造を見て分かる
- サブメニューの「APIキーの管理」ページのコンテンツは API キーの管理にフォーカスできる
- サブメニューに「地図」の文言が出ることにより、地図を作成したいユーザーを惑わせない。

![スクリーンショット 2021-08-03 9 26 35](https://user-images.githubusercontent.com/8760841/127939456-19f70b7e-d564-4475-bab2-605bc97d8959.png)


メニューの構造は、Auth0 のメニューを参考にしました。

![スクリーンショット 2021-08-03 9 32 50](https://user-images.githubusercontent.com/8760841/127939914-a9313896-2695-4393-9a0b-b31409166064.png)

**Comment by kai4den** [comment]
@naogify 

> - 地図
>  - API キーの管理

だと、何も知らない人が見たときにAPIキーが唐突に出てくるなという印象が強いなと思います（ダッシュボードTOPのテキストで説明はできるのですが、メニューだけで見たときのUXとして）。

「地図を発行したい」ので「地図の設定しよう」、その設定の中で「APIを管理する」というのがユーザー脳内の流れかなーというのがありまして、できれば最初にログインした状態では専門用語少なめにしておきたいなーとおもいますがいかがでしょうか。

ちなみに下の位置情報は

> - 位置情報データ
> 　- 位置情報データの管理

となっているので

> - 地図
>  - 地図の管理

とかでもいいのかなとおもいました。用語的にはこっちのほうが整合性はとれそう。

**Comment by naogify** [comment]
@kai4den 

> だと、何も知らない人が見たときにAPIキーが唐突に出てくるなという印象が強いなと思います（ダッシュボードTOPのテキストで説明はできるのですが、メニューだけで見たときのUXとして）。

> 「地図を発行したい」ので「地図の設定しよう」、その設定の中で「APIを管理する」というのがユーザー脳内の流れかなーというのがありまして、できれば最初にログインした状態では専門用語少なめにしておきたいなーとおもいますがいかがでしょうか。

ありがとうございます。

甲斐さんの課題感として、下の様なものがあるのかなと思いました。（他にもあれば指摘ください…！）

1. 地図を発行したいと思った時のファーストアクションが見当たらない。
2. サイドメニューで「地図」のサブメニューとして「APIキーの管理」が表示されていると関連性が分かりづらく、ユーザーに戸惑わせる。

## 1. ファーストアクションが見当たらない
まず、1 の「ファーストアクションが見当たらない」問題で言うと、進行中の作業ですが以下の様に、トップに「地図を作成する」というボタンを追加の予定です。こちらで解決できるかなと思っています…！

詳細：https://github.com/geolonia/app.geolonia.com/pull/462

![スクリーンショット 2021-08-03 13 55 36](https://user-images.githubusercontent.com/8760841/127962944-0b51ee11-bfd2-48d5-a6e0-87d59c7498bd.png)


## 2. 地図」のサブメニューとして「APIキーの管理」の関連性が分かりづらい

2 についての、「「地図」のサブメニューとして「APIキーの管理」の関連性が分かりづらい」ですが、一般のユーザーから見ると分かりづらいと感じるかもしれませんが、

開発者が見ると 地図 に APIキーが必要なんだ、とメニューの構造を見ただけで分かるので良いかなと思ってます。

こちらの件、説明が難しいので、よければ 一度 Around 等で説明させて頂けないでしょうか？

**Comment by ShinichiNishikawa** [comment]
```
- 地図
  - API キーの管理
```

or 

```
- 地図作成
  - 設定
```

なのか。

左メニューのカテゴリタイトル（クリッカブルじゃないとこ）に「地図」の文言が入るのは決まったのが大きいですね。そうすると、クリックするところが

* 「では、APIだな」というエンジニア脳なのか
* 「地図作ろっと」というAPIキーの概念がない人なのか

っていうことで理解しました。ログインした人、色々見て回る人にとってこのリンクをクリックするというアクションのところで引っかかりがあるかないか。どっちが分かりやすいのか、と。

最初から「じゃあ、APIキーを発行しよう」と思ってもらえる仮説と、それは無理だから中に入ってからAPI→貼り付けと誘導しよう仮説。

* 私は「APIキーを発行する場所なんだと理解してもらうべき仮説」
* API わかんない人は使ってくれないと思う
* 設定という一般ワードよりは、中身を指示する内容のほうがいいというセオリーを聞いたことがある

というので、前者支持です。3点目から行くと「APIキーとHTMLの生成」になりそうなんだけど。

今、https://github.com/geolonia/app.geolonia.com/pull/462 で頑張ってるのが、「1. キー発行」 → 「2. コピペ」 → 「3. ドキュメンテーション見て作業」というこのサービスの使い方が伝わるようにすることです。こっちも頑張れば、コンセプトが明確になって、問題が解消するように思います。

**Comment by kai4den** [comment]
スタンスの違いなのであとは多数決でいいかなーと思いつつとりあえず意見だけ書いときます。

> トップに「地図を作成する」というボタンを追加の予定です

で解決ある程度できるのですが、それって製品使うのに説明書読まなきゃ使えないみたいなUI/UXなので、できればこういう説明文章読まずにある程度把握できるのが理想だなーと思います（今回はいったんこれでいいかなとは思いますが理想像として）。

あと、それだと左メニューに「API」と表示したい、ということの意味がなくなっちゃうかなとも思います。

なので知りたいのは、設定メニューに「API」と出すことで得られるメリットがなんなのか、ですかね。それが個人的にはメインメニューで内包できる範囲なのかな、と思っていました。

ユーザーターゲットとして「地図を作ると言えばAPIだよねやっぱり」という理解がメジャーならAPI出した方がいいと思うのですが、開発者であってもそうはならない気はするんですよねー。

と長々書きましたが最終はお任せします。
