### ISSUE TITLE
プラン変更出来なかったときのエラーメッセージを出す

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#457]
オーナーとして、プランを`Pro (チーム5ユーザーまで)`にしたあと、別のプランに変更することができない。フリープランにも「Pro (チーム1ユーザーまで)」にも変更できない。

**Comment by keichan34** [comment]
もしチームメンバーが2人以上いるとダウングレードは出来ないのでそれに引っかかったのかな。。ただエラーは出ないので、出したほうがいいですね。。

**Comment by ShinichiNishikawa** [comment]
理解しました。エラーメッセージが出せればお願いします。解約できないと思われてしまうので優先度高いです。
