### ISSUE TITLE
支払履歴の"Time on Geolonia Pro after 02 Aug 2021"の金額計算

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#458]
金額が53円になっていて、1000/31 や 2000/30 等とも合わないので、確認してください。

![スクリーンショット 2021-08-03 10 51 35](https://user-images.githubusercontent.com/1124652/127945089-5d43dc8e-e02d-412a-b31b-5a4521447d61.png)

**Comment by keichan34** [comment]
ちょっとややこしいんだけど、この間説明したときに日割り按分と説明したと思いますが、具体的には秒割按分なんですね。。

登録された時点から08/04の00:00まで 142832 秒あって、08/04 00:00~09/04 00:00 まで 31日あって、31 * 86400 = 2678400 秒あります

```
1000/2678400 = .00037335722819593787円/秒
53/142832 = .00037106530749411896円/秒
```

差は 0.6% ぐらいしか無いのでおそらく大丈夫かなと思いますがいかがでしょう？

ちなみに、按分ロジックはStripeの方で計算されているのでこっちで修正したりできるのはビリングサイクルがいつになるかぐらいですね。現在、毎月の4日にしている理由は先月の利用分の集計が確定してから請求する、という狙いでした。

**Comment by ShinichiNishikawa** [comment]
なるほど、そしたら合ってるんですね。

サイトや料金表などの説明文で対応したいとおもいます。閉じてもらって大丈夫です。
