### ISSUE TITLE
表記の揺れチェック

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#473]
テキストの最終チェックとして表記揺れチェックをする。
何か気づいたら追記お願いします。

---

- ダッシュボード <- 管理画面

**Comment by kai4den** [comment]
サインイン後、右上のアイコンクリックで「ログアウト」と表示されるので、「サインアウト」にそろえたい

**Comment by kai4den** [comment]
左サイドメニューをクリックしたときの右メイン画面の見出し

* 一般：一般
* メンバー：Members
* 支払い：Billing

となるのでそろえたい（日本語でそろえるほうがいい？）

**Comment by kamataryo** [comment]
#484 「ご紹介」

**Comment by kamataryo** [comment]
今日の時点で分かっている揺れについて対応します！

**Comment by kamataryo** [comment]
この Issue はメモに使いたい。
- 地図の読み込み -> 地図の表示 https://github.com/geolonia/app.geolonia.com/issues/495#issuecomment-898094551
