### ISSUE TITLE
ダッシュボード左下のGeoJSON API説明文言について

### ISSUE THREAD

**Issue by kai4den** [geolonia/app.geolonia.com#483]
少し長めですが以下の文言でいかがでしょう

> 8月5日にダッシュボードのリニューアルを実施、正式版として公開しました。
> 
> ベータ版で提供していたGeoJSON APIは現在機能拡充に向けて開発を行っており、近日中に正式機能として公開予定です。
> 
> ベータ版で作成したデータはそのままお使いいただけますが、ダウンロードが必要な場合はお手数ですが別途ご連絡をお願いします。

**Comment by naogify** [comment]
@kai4den 
ありがとうございます…！流し込んで文量など確認してみます。
