### ISSUE TITLE
メンバー説明文

### ISSUE THREAD

**Issue by kai4den** [geolonia/app.geolonia.com#485]
> 現在、新しいメンバーを招待することはできません。メンバーをチームに招待するには、Geolonia Pro（2～5ユーザー）プランにアップグレードしてください。

を、具体的に何をすればいいのか追記とリンク入れたい。

> 現在、新しいメンバーを招待することはできません。メンバーをチームに招待するには、「支払い」の「プランを変更」から「Geolonia Pro（2～5ユーザー）プラン」にアップグレードしてください。

**Comment by kamataryo** [comment]
現在、フリープランでも招待できるようになり、その手順が簡略になったため、こちらクローズします。

<img width="686" alt="スクリーンショット 2021-09-07 11 25 14" src="https://user-images.githubusercontent.com/6292312/132274698-dcc179c2-602b-4626-98f0-409093812ec5.png">
