### ISSUE TITLE
地図の表示回数をダッシュボードで確認できるようにする

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#495]
クレジットカードを登録したユーザーとしては、地図の表示回数が見たい。

**Comment by keichan34** [comment]
@ShinichiNishikawa @kamataryo 文言大丈夫ですか。。？ :bow:

<img width="687" alt="Screen Shot 2021-08-13 at 9 58 05" src="https://user-images.githubusercontent.com/1064513/129288312-d5620d1e-bff8-4875-bf5c-d09c59168248.png">

**Comment by kamataryo** [comment]
@keichan34 地図の読み込み回数 -> 表示回数 はどうでしょう？

**Comment by keichan34** [comment]
あ、そうですね。他のところも全部表示回数なのでそっちに合わせます。ありがとうございます 👍
