### ISSUE TITLE
.test もYOUR-API-KEYで利用できるようにする

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#497]
valet ユーザーはこのドメインがたくさん出てくるということらしいです。
試しやすくなるのでやりたい。

**Comment by keichan34** [comment]
https://en.wikipedia.org/wiki/.test

なるほど。 `.example` もありかも。

**Comment by ShinichiNishikawa** [comment]
> 助かります！Laraveler は結構使ってるのでぜひ！ https://laravel.com/docs/master/valet#introduction

とのことでした。

**Comment by keichan34** [comment]
注意： free-referes を使ってないやつもあるので要確認

**Comment by kamataryo** [comment]
- [ ] https://github.com/geolonia/free-referers 修正
- [ ] api.geolonia.com の際ビルドとデプロイ
- [ ] tileserver-infra 対応 https://github.com/geolonia/tileserverless-infra/blob/9456b96ae4980b5f20e2fcb113d31e162b4e51da/src/authorizer.js#L19

**Comment by kamataryo** [comment]
動作 OK
```shell
$ curl 'https://tileserver.geolonia.com/v2/tiles.json?key=YOUR-API-KEY' -H 'origin: http://hello.test'
{"attribution":"<a href=\"https://geolonia.com/credit/\" target=\"_blank\">&copy; Geolonia</a> | <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap</a>","bounds":[122.5607,20.08228,154.4709,45.80245],"description":"Tiles built by Geolonia.","format":"pbf","scheme":"xyz","version":"3.0+9a8f907cb0c149602c32c10ff3a97f7a","maxzoom":14,"minzoom":8,"center":[138.5158,32.942365,11],"tiles":["https://tileserver.geolonia.com/v2/tiles/{z}/{x}/{y}.pbf?v=3.0%2B9a8f907cb0c149602c32c10ff3a97f7a&key=YOUR-API-KEY"]}
```

**Comment by kamataryo** [comment]
@ShinichiNishikawa こちら対応が終わりました。 .test と .example で YOUR-API-KEY が利用可能になりました。

**Comment by ShinichiNishikawa** [comment]
@kamataryo ありがとうございました！
