### ISSUE TITLE
Stripe の残高がある場合はダッシュボードに表示させる

### ISSUE THREAD

**Issue by keichan34** [geolonia/app.geolonia.com#501]

**Comment by keichan34** [comment]
@kamataryo @ShinichiNishikawa 文言の提案があれば、、。

<img width="989" alt="Screen Shot 2021-08-12 at 11 15 24" src="https://user-images.githubusercontent.com/1064513/129128142-293532a9-fe1e-4b0d-8537-86a60d504f75.png">

**Comment by kamataryo** [comment]
@keichan34 いいと思います！
