### ISSUE TITLE
モーダル表示のパディング調整　

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#508]
<img width="702" alt="スクリーンショット 2021-08-13 10 13 29" src="https://user-images.githubusercontent.com/6292312/129291116-0a066681-7f54-489a-bff2-1d302b425407.png">

**Comment by kamataryo** [comment]
おそらく、支払いのページのモーダルだけおかしい。他のモーダルは普通。

<img width="961" alt="スクリーンショット 2021-09-10 17 33 20" src="https://user-images.githubusercontent.com/6292312/132825202-63ff3651-db2c-4092-b01f-45fa281684a3.png">

**Comment by keichan34** [comment]
@kamataryo あ、すみません、 Billing.tsx は今かなり大きい改修しているので修正はこちらの後でも大丈夫でしょうか。。 :bow:

**Comment by kamataryo** [comment]
了解です。こちら止めておきます。
