### ISSUE TITLE
mbtilesアップロード

### ISSUE THREAD

**Issue by keichan34** [geolonia/app.geolonia.com#509]
geojson/ csv / mbtiles アップロードしてください

- [x] https://github.com/geolonia/api.geolonia.com/pull/201
- [x] https://github.com/geolonia/geojson-vector-pipeline/pull/35
- [x] https://github.com/geolonia/app.geolonia.com/pull/527
- [x] https://github.com/geolonia/geojson-vector-pipeline/issues/36
- [x] https://github.com/geolonia/embed/issues/231
- [x] https://github.com/geolonia/app.geolonia.com/issues/539

**Comment by kamataryo** [comment]
完了
