### ISSUE TITLE
ユーザーのAPIキーに、無料になるGithub PagesなどのURLが含まれていた場合にカウントを除外する

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#511]
無料になるものをカウントしてしまうケースがある。

* Github pages 
* Codepen
* .example
* .test
* .localhost:8080

などのドメイン名を使っていて、ユーザーが発行したAPIキーでリクエストされた場合に、カウントしてしまわないようにする。

**Comment by keichan34** [comment]
geolonia/api.geolonia.com#193
