### ISSUE TITLE
メンバー＞権限で支払いに関する権限があるのが分かるようにする

### ISSUE THREAD

**Issue by atsufumiyoshikawa** [geolonia/app.geolonia.com#528]
メンバー＞権限で支払いに関する権限があるのが分かるようにする

![admin-member](https://user-images.githubusercontent.com/8207033/130067296-3399e874-1ca4-4157-9c05-782967568b9d.png)

**Comment by kamataryo** [comment]
こちら、今回リリースで反映されました。

<img width="655" alt="スクリーンショット 2021-09-07 11 09 51" src="https://user-images.githubusercontent.com/6292312/132273536-f02ec544-76c7-4d62-9ba1-51e6907b149d.png">
