### ISSUE TITLE
UI 上 free プランでも招待可能になっている

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#562]
サーバーは意図どおり402を返すので招待は実行されない。
招待ボタンをdisabledにする。

**Comment by keichan34** [comment]
@kamataryo あれ、確かfreeでも招待可能にすると思います。。ちょっと確認します

**Comment by keichan34** [comment]
サーバーの方を調整する

**Comment by kamataryo** [comment]
https://github.com/geolonia/api.app.geolonia.com/issues/176
