### ISSUE TITLE
API キーの設定、allowed origin の説明を「URL」ではなくて「ドメイン」に変更

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#582]
> 地図の表示を許可するURLのリスト

を

> 地図の表示を許可するドメインのリスト

に変更。

![スクリーンショット 2021-09-14 21 46 04](https://user-images.githubusercontent.com/1124652/133260181-cf2060e6-f4f9-4b4f-b167-0c330131d9f8.png)

**Comment by kamataryo** [comment]
- パスを入力したときにはクライアント側でバリデーションして警告する

**Comment by kamataryo** [comment]
正確にはドメインではなくオリジン（スキーマ+FQDN+ポート）なのですが、表現としては「URL」 がやはり良いものと判断しました。これは docs.geolonia.com でも採用しています。
あくまで入力のバリデーションとして対応しました。

closed via #598

![path](https://user-images.githubusercontent.com/6292312/133711919-63273a5c-e228-4805-8c07-2d7d224977d6.gif)
