### ISSUE TITLE
ダッシュボード上のウィザードの順番が実際の作業と一致していない

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#586]
スクリプトタグ -> HTML の順番で紹介しているため、 `div.geolonia` より先に `<script src="https://cdn.geolonia.com/...">` を記述してしまうことがある。

**Comment by kamataryo** [comment]
- CSS を スタイル属性内部に記述
- ステップ１と２ を入れ替える

**Comment by miya0001** [comment]
これって実際のサイトに組み込む場合には `<div>` の場所はデザイン上決まっているはずで、こういうミスはあまり発生しないかなと思いました。
そして Google Maps も JavaScript API から設置していますね。

https://developers.google.com/maps/documentation/javascript/overview?hl=ja#maps_map_simple-javascript

明確に `</body>` の直前に設置してもらうことを伝えることが重要かなと。
