### ISSUE TITLE
料金ページのリクエスト回数表示グラフで、過去の実績も見れる or 日付範囲指定で表示ができるようにしたい

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#685]
実績 ↓

![スクリーンショット_2022-09-26_15_47_12](https://user-images.githubusercontent.com/1124652/192212269-0d32fb15-bfed-4154-b65d-6f6161a67c1f.png)

app.geolonia.com 上での表示 ↓

![スクリーンショット_2022-09-26_15_53_08](https://user-images.githubusercontent.com/1124652/192212177-8a7751f0-ace9-4ede-a77f-48b0cce1c90d.png)

今回の条件は、

* クレジットカードではなく、請求書払
* 「前月26日から当月25日までの分を当月末に請求して、翌月末までに支払ってもらう」というルール
* ユーザーがAPIキーを発行したのは過去の23日

なので、ユーザーは、前月末の利用実績を確認したいはず。
今表示しているのは、今月分のみ、1ヶ月分なので、それができない。

**Comment by kamataryo** [comment]
#694 で対応しました 🙇
