### ISSUE TITLE
クライアント側での制限モード判定が不正で、Pro プランの時が考慮されていない

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#695]
Pro プラン（従量課金）の時は以下の天井の警告表示をしないようにする。

<img width="556" alt="スクリーンショット 2022-11-01 11 06 58" src="https://user-images.githubusercontent.com/6292312/199143023-90c85532-3ff2-4934-a66b-ffa764582c31.png">

https://github.com/geolonia/app.geolonia.com/commit/1e5135b5d122544e822fa7fa5e4e54d2c830a7d1#diff-7082c40ef31cf4346447fc8d96e6a8089798caa5c35cc0166febb4e44f205781R50-R55

**Comment by kogumari** [comment]
ありがとうございます！
ちなみに、50,001回からは従量課金になりますが、これはどういうように処理されるようになているかも、今のうちに確認しておくと良さそうに思いました。

**Comment by kamataryo** [comment]
こちらの件、 #698 で解消しました。
@kogumari 従量課金関連の件は以下にまとめていて、課題があるためこちらをベースに議論を進めたいです。
https://github.com/geolonia/api.app.geolonia.com/issues/249
