### ISSUE TITLE
アクセス量グラフの下の数字を3桁区切りに

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/app.geolonia.com#708]
https://app.geolonia.com/#/team/billing
2箇所ある。
![イメージ](https://user-images.githubusercontent.com/1124652/207550783-92668c35-41cc-40f8-b6c3-995edb322c07.jpg)

**Comment by kamataryo** [comment]
@ShinichiNishikawa こちら対応しました。キャッシュが切れると反映されると思います。

**Comment by ShinichiNishikawa** [comment]
確認しました！
