### ISSUE TITLE
API リクエストの際のサイズ制限

### ISSUE THREAD

**Issue by kamataryo** [geolonia/app.geolonia.com#71]
画像や、テキストのサイズを適宜 API 側、クライアント側でバリデーションする。

**Comment by miya0001** [comment]
画像に対してはクライアント側で、10MBの制限。
API 側は CloudFront の制限そのまんま。

**Comment by kamataryo** [comment]
API Gateway のソフトリミット: (ペイロードは 10MB らしい)
https://docs.aws.amazon.com/ja_jp/apigateway/latest/developerguide/limits.html
